# Generated by Django 4.0.4 on 2022-05-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sol', models.FileField(upload_to='vul_upload/')),
                ('fpath', models.CharField(max_length=100, null=True)),
                ('result', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
