# Generated by Django 4.0.4 on 2022-05-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulscan', '0003_remove_solupload_sol_solupload_add_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolUpload',
            new_name='SolAddList',
        ),
    ]
