# Generated by Django 4.0.4 on 2022-05-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulscan', '0004_rename_solupload_soladdlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='soladdlist',
            name='time',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
