# Generated by Django 4.0.4 on 2022-05-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulscan', '0012_alter_soladdlist_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='soladdlist',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
