# Generated by Django 4.0.4 on 2022-05-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulscan', '0013_soladdlist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='soladdlist',
            name='runtime',
            field=models.CharField(max_length=99999999, null=True),
        ),
    ]
