# Generated by Django 4.0.4 on 2022-05-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulscan', '0015_alter_soladdlist_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soladdlist',
            name='runtime',
            field=models.TextField(blank=True, null=True),
        ),
    ]
