# Generated by Django 4.0.4 on 2022-05-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulscan', '0016_alter_soladdlist_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='soladdlist',
            name='check_time',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
