# Generated by Django 4.0.4 on 2022-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulscan', '0018_soladdlist_cfg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soladdlist',
            name='cfg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
