# Generated by Django 4.0.4 on 2022-05-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VulDeatilList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rid', models.IntegerField(null=True)),
                ('swcid', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('impact', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('lines', models.CharField(max_length=99999999999999, null=True)),
            ],
        ),
    ]
