# Generated by Django 4.0.4 on 2022-05-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuldeatillist',
            name='add',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vuldeatillist',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vuldeatillist',
            name='fpath',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vuldeatillist',
            name='scantype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
