# Generated by Django 4.0.4 on 2022-05-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulreport', '0002_vuldeatillist_add_vuldeatillist_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuldeatillist',
            name='lines',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
