# Generated by Django 4.0.4 on 2022-05-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulreport', '0003_alter_vuldeatillist_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuldeatillist',
            name='add',
        ),
        migrations.RemoveField(
            model_name='vuldeatillist',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='vuldeatillist',
            name='fpath',
        ),
        migrations.RemoveField(
            model_name='vuldeatillist',
            name='scantype',
        ),
    ]
