# Generated by Django 4.0.4 on 2022-05-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtherVerified',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('compiler', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(max_length=100, null=True)),
                ('verified_time', models.CharField(max_length=20, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
