# Generated by Django 4.0.4 on 2022-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etherverified',
            name='add',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
