# Generated by Django 4.0.4 on 2022-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytools', '0002_alter_etherverified_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='etherverified',
            name='fpath',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
